#!/usr/bin/env bash
#PBS -l nodes=1:ppn=128
#PBS -l walltime=00:30:00
#PBS -A astaff
#PBS -e ${PBS_JOBNAME}.${PBS_JOBID}.stderr
#PBS -o ${PBS_JOBNAME}.${PBS_JOBID}.stdout
#PBS -M engelbert.tijskens@uantwerpen.be
#PBS -m bea

# unset SLURM_EXPORT_ENV
echo "JOB ID = $SLURM_JOB_ID"

source /dodrio/scratch/users/vsc20170/prj-vmm/bert/.local/bin/setup-python-vmm.sh

cd $PBS_O_WORKDIR

worker_nodes=$(uniq $PBS_NODEFILE)
echo "worker_nodes = ${worker_nodes}"

mympirun --universe 6 python t.py