#!/usr/bin/env bash
#PBS -l nodes=1:ppn=20
#PBS -l walltime=00:05:00
#PBS -A astaff
#PBS -e ${PBS_JOBNAME}.${PBS_JOBID}.stderr
#PBS -o ${PBS_JOBNAME}.${PBS_JOBID}.stdout

echo "JOB ID = $SLURM_JOB_ID"

# load modules needed
source /dodrio/scratch/users/vsc20170/prj-vmm/bert/.local/bin/setup-python-vmm.sh

cd $PBS_O_WORKDIR

worker_nodes=$(uniq $PBS_NODEFILE)
echo "worker_nodes = ${worker_nodes}"

mympirun --universe 20 python two-levels.py